/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2019-06-10 03:35:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class crudProducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"esS\" >\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrapValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/dataTables.bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrapValidator.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.modal-header, h4, .close {\r\n");
      out.write("\t\tbackground-color: #286090;\r\n");
      out.write("\t\tcolor: white !important;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>     \r\n");
      out.write("\r\n");
      out.write("<title>Tenis </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write(" <h1>Crud de Producto</h1>\r\n");
      out.write("\t\t <div class=\"col-md-23\" >  \r\n");
      out.write("\t\t\t  <form id=\"idFormElimina\" action=\"eliminaProducto\">\r\n");
      out.write("\t\t\t  \t\t<input type=\"hidden\" id=\"id_elimina\" name=\"id\">\r\n");
      out.write("\t\t\t  </form>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t       <form accept-charset=\"UTF-8\"  action=\"consultaProducto\" class=\"simple_form\" id=\"defaultForm2\"  method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t<label class=\"control-label\" for=\"id_nombre_filtro\">Nombre</label>\r\n");
      out.write("\t\t\t\t\t\t\t  \t<input class=\"form-control\" id=\"id_nombre_filtro\"  name=\"filtro\" placeholder=\"Ingrese el nombre\" type=\"text\" maxlength=\"70\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" id=\"validateBtnw1\" >FILTRA</button><br>&nbsp;<br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" data-toggle='modal' onclick=\"registrar();\"  class='btn btn-success' id=\"validateBtnw2\" >REGISTRA</button><br>&nbsp;<br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" data-toggle='modal' onclick=\"registrarCate();\"  class='btn btn-success' id=\"validateBtnw3\" >Nueva Categoria</button><br>&nbsp;<br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"window.location.href='/PI_TennisMesa/Mantenimiento.jsp'\">VOLVER</button><br>&nbsp;<br>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" > \r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content\" >\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"table\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t \t\t</form>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("  \r\n");
      out.write("  \t\t <div class=\"modal fade\" id=\"idModalRegistra\" >\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" style=\"width: 60%\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"padding: 35px 50px\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<h4><span class=\"glyphicon glyphicon-ok-sign\"></span> Registro de Producto</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 20px 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"defaultForm\" accept-charset=\"UTF-8\" action=\"registraProducto\" class=\"form-horizontal\"     method=\"post\">\r\n");
      out.write("\t\t                    <div class=\"panel-group\" id=\"steps\">\r\n");
      out.write("\t\t                        <!-- Step 1 -->\r\n");
      out.write("\t\t                        <div class=\"panel panel-default\">\r\n");
      out.write("\t\t                            <div class=\"panel-heading\">\r\n");
      out.write("\t\t                                <h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#steps\" href=\"#stepOne\">Datos del Producto</a></h4>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                            <div id=\"stepOne\" class=\"panel-collapse collapse in\">\r\n");
      out.write("\t\t                                <div class=\"panel-body\">\r\n");
      out.write("\t\t                                     <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_reg_nombre\">Nombre</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"id_reg_nombre\" name=\"nombre\" placeholder=\"Ingrese el Nombre\" type=\"text\" maxlength=\"70\"/>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_reg_descripcion\">Descripción</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea id=\"id_reg_descripcion\" name=\"descripcion\" cols=\"60\" rows=\"10\" placeholder=\"Ingrese una descripcion\" maxlength=\"20000\" ></textarea>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_reg_precio\">Precio</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"id_reg_precio\" name=\"precio\" placeholder=\"Ingrese el precio\" type=\"text\" maxlength=\"70\"/>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_reg_stock\">Stock</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"id_reg_stock\" name=\"stock\" placeholder=\"Ingrese el stock\" type=\"text\" maxlength=\"70\"/>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <label class=\"col-lg-3 control-label\" for=\"id_reg_imagen\">Seleccione Imagen</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t             <input type=\"file\" name=\"imagen\" id=\"id_reg_imagen\" onchange=\"processFiles(this.files)\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <label class=\"col-lg-3 control-label\" for=\"id_reg_previaFoto\">Previsualizacion</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t             <output id=\"list\"></output>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_reg_categoria\">Categoria</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"id_cboCategoria\" name=\"categoria\"   class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\" \" >[ Seleccione ]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <div class=\"col-lg-9 col-lg-offset-3\">\r\n");
      out.write("\t\t                                        \t<button type=\"submit\" class=\"btn btn-primary\">REGISTRA</button>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                </div>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        \r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </form>   \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("  \r\n");
      out.write("\t\t <div class=\"modal fade\" id=\"idModalActualiza\" >\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" style=\"width: 60%\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"padding: 35px 50px\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<h4><span class=\"glyphicon glyphicon-ok-sign\"></span> Actualiza Producto</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 20px 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"defaultForm\" accept-charset=\"UTF-8\"  action=\"actualizaProducto\" class=\"form-horizontal\"     method=\"post\">\r\n");
      out.write("\t\t                    <div class=\"panel-group\" id=\"steps\">\r\n");
      out.write("\t\t                        <!-- Step 1 -->\r\n");
      out.write("\t\t                        <div class=\"panel panel-default\">\r\n");
      out.write("\t\t                            <div class=\"panel-heading\">\r\n");
      out.write("\t\t                                <h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#steps\" href=\"#stepOne\">Datos del Producto</a></h4>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                            <div id=\"stepOne\" class=\"panel-collapse collapse in\">\r\n");
      out.write("\t\t                                <div class=\"panel-body\">\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_ID\">ID</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t                                           <input class=\"form-control\" id=\"id_ID\" readonly=\"readonly\" name=\"id\" type=\"text\" maxlength=\"8\"/>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                     </div>\r\n");
      out.write("\t\t                                     <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_nombre\">Nombre</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"id_nombre\" name=\"nombre\" placeholder=\"Ingrese el Nombre\" type=\"text\" maxlength=\"70\"/>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_descripcion\">Descripcion</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea id=\"id_descripcion\" name=\"descripcion\" cols=\"60\" rows=\"10\" placeholder=\"Ingrese la descripcion\" maxlength=\"20000\" ></textarea>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_precio\">Precio</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea id=\"id_precio\" name=\"precio\" cols=\"60\" rows=\"10\" placeholder=\"Ingrese el precio\" maxlength=\"20000\" ></textarea>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_stock\">Stock</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea id=\"id_stock\" name=\"stock\" cols=\"60\" rows=\"10\" placeholder=\"Ingrese el stock\" maxlength=\"20000\" ></textarea>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_categoria\">Categoria</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"id_cboCategoria\" name=\"categoria\"   class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\" \" >[ Seleccione ]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <div class=\"col-lg-9 col-lg-offset-3\">\r\n");
      out.write("\t\t                                        \t<button type=\"submit\" class=\"btn btn-primary\">ACTUALIZA</button>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                </div>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        \r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </form>   \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"idModalRegistraCate\" >\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" style=\"width: 60%\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"padding: 35px 50px\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<h4><span class=\"glyphicon glyphicon-ok-sign\"></span> Registro de Categoria</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 20px 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"defaultForm\" accept-charset=\"UTF-8\" action=\"registraCate\" class=\"form-horizontal\"     method=\"post\">\r\n");
      out.write("\t\t                    <div class=\"panel-group\" id=\"steps\">\r\n");
      out.write("\t\t                        <!-- Step 1 -->\r\n");
      out.write("\t\t                        <div class=\"panel panel-default\">\r\n");
      out.write("\t\t                            <div class=\"panel-heading\">\r\n");
      out.write("\t\t                                <h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#steps\" href=\"#stepOne\">Datos de la Nueva Categoria</a></h4>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                            <div id=\"stepOne\" class=\"panel-collapse collapse in\">\r\n");
      out.write("\t\t                                <div class=\"panel-body\">\r\n");
      out.write("\t\t                                     <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label class=\"col-lg-3 control-label\" for=\"id_reg_nombreCat\">Nombre</label>\r\n");
      out.write("\t\t                                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"id_reg_nombreCat\" name=\"nombreCat\" placeholder=\"Ingrese el Nombre\" type=\"text\" maxlength=\"70\"/>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <div class=\"col-lg-9 col-lg-offset-3\">\r\n");
      out.write("\t\t                                        \t<button type=\"submit\" class=\"btn btn-primary\">REGISTRA</button>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                </div>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        \r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </form>   \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function eliminar(id){\t\r\n");
      out.write("\t$('input[id=id_elimina]').val(id);\r\n");
      out.write("\t$('#idFormElimina').submit();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function registrar(){\r\n");
      out.write("\t$('#idModalRegistra').modal(\"show\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function registrarCate(){\r\n");
      out.write("\t$('#idModalRegistraCate').modal(\"show\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function editar(id,nombre,descripcion,precio,stock,idCategoria){\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('input[id=id_ID]').val(id);\r\n");
      out.write("\t$('input[id=id_nombre]').val(nombre);\r\n");
      out.write("\t$('input[id=id_descripcion]').val(descripcion);\r\n");
      out.write("\t$('input[id=id_precio]').val(precio);\r\n");
      out.write("\t$('[id=id_stock]').val(stock);\r\n");
      out.write("\t$('[id=id_categoria]').val(categoria.idCategoria);\r\n");
      out.write("\t$('#idModalActualiza').modal(\"show\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).ready( function(){\r\n");
      out.write("\t$.getJSON(\"cargaCategoria\",{}, function (data){\r\n");
      out.write("\t\tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t$.each(data.lstCategoria, function(index, item){\r\n");
      out.write("\t\t\t$(\"#id_cboCategoria\").append(\"<option value=\"+item.idCategoria+\">\"+ item.nombre +\"</option>\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#defaultForm').bootstrapValidator({\r\n");
      out.write("        message: 'This value is not valid',\r\n");
      out.write("        excluded: ':disabled',\r\n");
      out.write("        feedbackIcons: {\r\n");
      out.write("            valid: 'glyphicon glyphicon-ok',\r\n");
      out.write("            invalid: 'glyphicon glyphicon-remove',\r\n");
      out.write("            validating: 'glyphicon glyphicon-refresh'\r\n");
      out.write("        },\r\n");
      out.write("        fields: {\r\n");
      out.write("        \tnombre: {\r\n");
      out.write("        \t\tselector : '#id_reg_nombre',\r\n");
      out.write("                validators: {\r\n");
      out.write("                    notEmpty: {\r\n");
      out.write("                        message: 'El nombre es un campo obligatorio'\r\n");
      out.write("                    },\r\n");
      out.write("                    stringLength :{\r\n");
      out.write("                    \tmessage:'El nombre es de 5 a 100 caracteres',\r\n");
      out.write("                    \tmin : 5,\r\n");
      out.write("                    \tmax : 100\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            descripcion: {\r\n");
      out.write("        \t\tselector : '#id_reg_descripcion',\r\n");
      out.write("                validators: {\r\n");
      out.write("                    notEmpty: {\r\n");
      out.write("                        message: 'La descripcion es un campo obligatorio'\r\n");
      out.write("                    },\r\n");
      out.write("                    stringLength :{\r\n");
      out.write("                    \tmessage:'La descripcion es de 5 a 100 caracteres',\r\n");
      out.write("                    \tmin : 5,\r\n");
      out.write("                    \tmax : 5000000\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("       \t}    \r\n");
      out.write("     }).on('error.form.bv', function(e) {\r\n");
      out.write("            console.log('error');\r\n");
      out.write("\r\n");
      out.write("            // Active the panel element containing the first invalid element\r\n");
      out.write("            var $form         = $(e.target),\r\n");
      out.write("                validator     = $form.data('bootstrapValidator'),\r\n");
      out.write("                $invalidField = validator.getInvalidFields().eq(0),\r\n");
      out.write("                $collapse     = $invalidField.parents('.collapse');\r\n");
      out.write("\r\n");
      out.write("            $collapse.collapse('show');\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function processFiles(files) {\r\n");
      out.write("\tvar files = files[0];\r\n");
      out.write("\tvar reader = new FileReader();\r\n");
      out.write("\treader.onload = function (e) {\r\n");
      out.write("\t\tdocument.getElementById(\"list\").innerHTML = \"<img src='\"+e.target.result+\"' width='500px' height='250px' />\";\r\n");
      out.write("\t};\r\n");
      out.write("\treader.readAsDataURL(files); \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /crudProducto.jsp(67,12) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productos}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /crudProducto.jsp(67,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("x");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"font-size:40px\" >Nombre: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"justify\">Descripción: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type='button' data-toggle='modal' onclick=\"editar('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.idProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.precio}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.categoria}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("');\" class='btn btn-success' style='background-color:hsla(233, 100%, 100%, 0);'>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img src='images/edit.gif' width='auto' height='auto' />\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type='button' data-toggle='modal' onclick=\"eliminar('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.idProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("');\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img src='images/delete.gif' width='auto' height='auto' />\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"justify\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tPrecio: S/.");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.precio}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"justify\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tStock: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"justify\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tCategoria: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.categoria.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
